export const ACTION_TYPES = {
    CHAPTERS: {
        SAVE_CHAPTERS_REQUEST: "SAVE_CHAPTERS_REQUEST",
        SAVE_CHAPTERS_SUCCESS: "SAVE_CHAPTERS_SUCCESS",
        SAVE_CHAPTERS_FAILURE: "SAVE_CHAPTERS_FAILURE",
    },
    RELATED_MEDIA: {
        SAVE_RELATED_MEDIA_SUCCESS: "SAVE_RELATED_MEDIA_SUCCESS",
        SAVE_RELATED_MEDIA_FAILURE: "SAVE_RELATED_MEDIA_FAILURE",
    },
    LOGIN: {
        LOGIN_REQUEST: "LOGIN_REQUEST",
        LOGIN_SUCCESS: "LOGIN_SUCCESS",
        LOGIN_FAILURE: "LOGIN_FAILURE",
    },
    SIGNUP: {
        SIGNUP_REQUEST: "SIGNUP_REQUEST",
        SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
        SIGNUP_FAILURE: "SIGNUP_FAILURE",
    },
};