export const ACTION_TYPES = {
    CHAPTERS: {
        SAVE_CHAPTERS_REQUEST: "SAVE_CHAPTERS_REQUEST",
        SAVE_CHAPTERS_SUCCESS: "SAVE_CHAPTERS_SUCCESS",
        SAVE_CHAPTERS_FAILURE: "SAVE_CHAPTERS_FAILURE",
    },
};